# Generated by Django 6.0.2 on 2026-03-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0005_alter_user_role_institutionsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('previous_qualification', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='academics.academicyear')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='accounts.institution')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='academics.program')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to='academics.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
