# Generated by Django 6.0.2 on 2026-03-21 19:11

import django.db.models.deletion
from django.db import migrations, models


def add_user_institution_column(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Institution = apps.get_model("accounts", "Institution")
    table_name = User._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
    if "institution_id" in existing_columns:
        return

    field = models.ForeignKey(
        Institution,
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="+",
    )
    field.set_attributes_from_name("institution")
    schema_editor.add_field(User, field)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_user_institution_column, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='institution',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='users',
                        to='accounts.institution',
                    ),
                ),
            ],
        ),
    ]
