# Generated by Django 6.0.2 on 2026-03-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_default_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hod', 'Head Of Department'), ('exam_officer', 'Exam Officer'), ('placement_officer', 'Placement Officer'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='InstitutionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('primary_color', models.CharField(default='#11243d', max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('attendance_threshold', models.PositiveSmallIntegerField(default=75)),
                ('grading_scheme', models.TextField(default='A+: 90-100\nA: 80-89\nB: 70-79\nC: 60-69\nD: 50-59\nF: Below 50')),
                ('current_academic_year', models.CharField(blank=True, max_length=20)),
                ('logo_url', models.URLField(blank=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.institution')),
            ],
        ),
    ]
