# Generated by Django 6.0.3 on 2026-05-15 09:45

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_institution_institution_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.TenantAwareUserManager()),
            ],
        ),
    ]
