# Generated by Django 6.0.2 on 2026-03-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_institution_user_institution'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='accounts.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('institution', 'name', 'date')},
        ),
    ]
