# Generated by Django 6.0.2 on 2026-03-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_institution_user_institution'),
        ('departments', '0002_department_institution_alter_department_name_and_more'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('institution', 'name', 'department')},
        ),
    ]
